apiVersion: backstage.io/v1beta2
kind: Template
# some metadata about the template itself
metadata:
  name: template-api-spec
  title: API Spec
  description: An API specification that can be searched via the catalogue
spec:
  owner: onboarding
  type: api

  # these are the steps which are rendered in the frontend with the form input
  parameters:
    - title: Please provide some details
      required:
        - name
        - repoUrl
      properties:
        name:
          title: Name
          type: string
          description: Unique name of the component
          ui:autofocus: true
          ui:options:
              rows: 5
      repoUrl:
        title: Repository Location
        type: string
        ui:field: RepoUrlPicker
        ui:options:
          allowedHosts:
            - github.com
  steps: []
