apiVersion: backstage.io/v1beta2
kind: Template
# some metadata about the template itself
metadata:
  name: template-api-spec
  title: Timestream event subscriber
  description: A component which subscribes to events and stores data in an AWS Timestream database
spec:
  owner: onboarding
  type: api

  # these are the steps which are rendered in the frontend with the form input
  parameters:
    - title: Please provide some details
      required:
        - name
      properties:
        name:
          title: Name
          type: string
          description: Unique name of the component
          ui:autofocus: true
          ui:options:
            rows: 5
  steps: []
